name: metris
description: "A Tetris game app with multiple features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  package_rename_plus: ^1.0.2
  icons_launcher: ^3.0.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

package_rename_config:
  android:
    app_name: metris # (String) The display name of the android app
    package_name: gr.techzombie.metris # (String) The package name of the android app

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
