// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can configure it in the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BMINjcPVzUHvTND-nazF5Hz3j2hH3M4',
    appId: '1:295741379623:web:7b97c521a53d11212aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    authDomain: 'metris2app.firebaseapp.com',
    storageBucket: 'metris2app.firebasestorage.app',
    measurementId: 'G-CZFTZ53EJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbBbIOxzjzhnYuEzrFQqI8ee5FKrSszQ',
    appId: '1:295741379623:android:953769214e9bb6d92aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    storageBucket: 'metris2app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbBiHv5rAF9HZr6IEteh8FuEzSp4732s',
    appId: '1:295741379623:ios:361a20c0e641d6632aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    storageBucket: 'metris2app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbBiHv5rAF9HZr6IEteh8FuEzSp4732s',
    appId: '1:295741379623:ios:361a20c0e641d6632aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    storageBucket: 'metris2app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-BMINjcPVzUHvTND-nazF5Hz3j2hH3M4',
    appId: '1:295741379623:web:52c48a46b1caaacb2aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    authDomain: 'metris2app.firebaseapp.com',
    storageBucket: 'metris2app.firebasestorage.app',
    measurementId: 'G-6NY6QTWD3B',
  );

}