// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BMINjcPVzUHvTND-nazF5Hz3j2hH3M4',
    appId: '1:295741379623:web:7b97c521a53d11212aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    authDomain: 'metris2app.firebaseapp.com',
    databaseURL: 'https://metris2app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metris2app.firebasestorage.app',
    measurementId: 'G-CZFTZ53EJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbBbIOxzjzhnYuEzrFQqI8ee5FKrSszQ',
    appId: '1:295741379623:android:953769214e9bb6d92aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    databaseURL: 'https://metris2app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metris2app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbBiHv5rAF9HZr6IEteh8FuEzSp4732s',
    appId: '1:295741379623:ios:361a20c0e641d6632aaa02',
    messagingSenderId: '295741379623',
    projectId: 'metris2app',
    databaseURL: 'https://metris2app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'metris2app.firebasestorage.app',
    androidClientId: '295741379623-fnnprp3bfbpnj9malaf5vrts484mj0qu.apps.googleusercontent.com',
    iosClientId: '295741379623-rg6br22t8g61j3fe0p7aqfons939muk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
