name: Build and distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: ./

      - name: Archive Production artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/web

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: tetris.kog.gr
          username: kosmas@tetris.kog.gr
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/web/
